### ISSUE TITLE
UTF-8 characters are removed when building project with Nexe (v1.1.2)

### ISSUE THREAD

**Issue by Skuldur** [jaredallard/nexe#224] opened 2016-05-24 11:29 UTC
Hi,

When we build our project with Nexe we have a bug show up that Inquirer (https://www.npmjs.com/package/inquirer#checkbox---type-checkbox) Checkboxes are not displayed at all. They work correctly if the code is run with Node, so this seems to be a problem with Nexe.

EDIT: Seems like the problem is that UTF-8 character in general are being removed (e.g. ð þ ö)

**Comment by jaredallard** [comment] 2016-05-24 18:24
Most likely a duplicate of  #206

**Closed by jaredallard** 2016-05-24 18:24 UTC
