### ISSUE TITLE
Failed to compile.

### ISSUE THREAD

**Issue by bharti795** [jaredallard/nexe#209] opened 2016-04-07 15:45 UTC
root@xyz:/home/xyz/Documents/offline# nexe -i ./app.js -o ./offline
----> framework => nodejs
----> bundle /home/xyz/Documents/offline/app.js
----> found browserify in /usr/lib/node_modules/nexe/node_modules/browserify/bin/cmd.js
----> Browserify finished
----> embedResources undefined
----> resource -> /home/xyz/Documents/offline/tmp/nexe/nodejs/latest/node-v5.10.1/lib/nexeres.js
ENOENT, open '/home/xyz/Documents/offline/tmp/nexe/nodejs/latest/node-v5.10.1/src/node.js'

**Comment by jaredallard** [comment] 2016-04-07 16:13
Duplicate of #207.

**Closed by jaredallard** 2016-04-07 16:13 UTC
