### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by MGasztold** [jaredallard/nexe#225] opened 2016-05-24 12:03 UTC
I am getting the following output from `nexe -i myscript.js`:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
SyntaxError: Unexpected character '�'
```

Only modules I use in the script are:
```
var bleacon = require('bleacon');
var async = require('async');
```
I have already tried replacing the above modules names to full path to their main .js files but im still getting same error.

Any idea how to investigate on this? Can it be because of something wrong in my script?

**Comment by jaredallard** [comment] 2016-05-24 18:24
Duplicate of #206 (hard to tell!)

**Closed by jaredallard** 2016-05-24 18:24 UTC
