### ISSUE TITLE
form-data (via request) build issue

### ISSUE THREAD

**Issue by deployable** [jaredallard/nexe#145] opened 2015-10-29 02:15 UTC
When using [request](https://github.com/request/request), it depends on [form-data](https://github.com/form-data/form-data)

A build throws an error `FormData is not defined` on  https://github.com/form-data/form-data/blob/master/lib/browser.js

Removing the [`browser` line from form-data/package.json](https://github.com/form-data/form-data/blob/master/package.json#L11) allows it to build

I saw https://github.com/jaredallard/nexe/issues/131 re moving to browserfy. I guess that might help?

**Comment by deployable** [comment] 2015-10-29 04:13
I've just noticed that nexe depends on request as well so this must work somewhere?

I'm using node 4.2.1 on osx and windows, both produce the same results:

```
nexe.js:48498
module.exports = FormData;}, false, {}],"/Users/matt/clones/nexe/node_modules/lcid/lcid.json": [function (require, module, exports, __dirname) { 
                 ^

ReferenceError: FormData is not defined
    at Array.__dirname.call./Users/matt/clones/nexe/node_modules/form-data/lib/browser.js (nexe.js:48498:18)
    at initModule (nexe.js:29:11)
    at nexe.js:31:64
    at Array.__dirname.call./Users/matt/clones/nexe/node_modules/request/request.js.http (nexe.js:7062:16)
    at initModule (nexe.js:29:11)
    at nexe.js:31:64
    at Array.__dirname.call./Users/matt/clones/nexe/node_modules/request/index.js.extend (nexe.js:7032:19)
    at initModule (nexe.js:29:11)
    at nexe.js:31:64
    at Array.__dirname.call./Users/matt/clones/nexe/lib/exe.js.path (nexe.js:172:21)
```

Maybe this is a node 4.x thing?

**Comment by deployable** [comment] 2015-10-29 04:58
So request 2.57 works. 2.58 moved to form-data `~1.0.0-rc1` which also worked.

The browser shim was added to form-data in 1.0.0-rc3 which any later install of request would automatically use.  https://github.com/form-data/form-data/commit/87c33f4269a2211938f80ab3e53835362b1afee8

**Comment by deployable** [comment] 2015-10-29 05:26
And adding browserify to my compile chain as suggested here https://github.com/jaredallard/nexe/issues/124#issuecomment-132785492 works fine.

**Comment by deployable** [comment] 2015-10-29 05:32
...on osx. 

On windows I'm seeing https://github.com/jaredallard/nexe/issues/124#issuecomment-127264361 from bluebird.

**Comment by jaredallard** [comment] 2015-10-30 20:56
So it does work with browserify?

**Comment by jaredallard** [comment] 2015-10-30 20:57
Because nexe won't build with browserify thanks to that same issue.

**Comment by deployable** [comment] 2015-10-30 23:28
Yes browserify resolved the form-data and bluebird promise issues for me. 

It raised a seperate issue where it doesn't appear to include ./lib files though as mentioned in https://github.com/jaredallard/nexe/issues/124#issuecomment-152149602

**Comment by deployable** [comment] 2015-10-30 23:43
I think setting NODE_PATH to `./lib` (or any of the require [workarounds](http://stackoverflow.com/questions/10860244/how-to-make-the-require-in-node-js-to-be-always-relative-to-the-root-folder-of-t)) and requiring non relative paths might make browserify include them.    I can't see a straight option that controls this but I assume when browserify builds for the browser it has to bundle the `./lib` files!?

**Comment by vilic** [comment] 2015-10-31 14:29
This issue is caused by `browser-resolve` depended by `module-deps` which is used by nexe, as the `package.json` file of `request` specifies a `browser` entry pointing to a file that will not work for node. But it should be covered in my pull request #143 (already merged but not yet published to npm)

**Comment by jaredallard** [comment] 2015-11-04 07:31
It's included in 0.4.2 now! :)

**Comment by vilic** [comment] 2015-11-04 08:54
:tada: :smile:

**Comment by jaredallard** [comment] 2016-01-25 04:12
This should be completely fixed and published!

**Closed by jaredallard** 2016-01-25 04:12 UTC
